[package]
name = "qwer-derive"
version.workspace = true
edition = "2021"
description = "Codegen for Zenless Zone Zero's Qwer Protocol"
license = "MIT"
publish = true

[lib]
proc-macro = true

[dependencies]
heck.workspace = true
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = "2.0.52"
